pipeline {
    agent any
    tools {
        maven "M3"
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage('Clone Repository') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']],
                userRemoteConfigs: [[url: 'https://github.com/swjadhav/Selenium-testNg-Maven.git']]])

            }
         }
        stage('Run Test') {
            steps {
                sh 'mvn clean install test'
                 }
        }
        stage('Publish Reports') {
             steps {
                sh 'echo Generating TestNG Report'
                 }
            post {
                always{
                    step([$class: 'Publisher', reportFilenamePattern: '**/testng-results.xml'])
                }
            }
        }
    }
}
